name: Build and Deploy
on:
  push:	
    branches:	
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: source # The branch the action should deploy from.
        BRANCH: master # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
        BUILD_SCRIPT: yarn && yarn build # The build script the action should run prior to deploying.